(function() {
    'use strict';

    angular.module('linagora.esn.emoticon').factory('esnEmoticonCategories', esnEmoticonCategories);

    function esnEmoticonCategories() {
        return {
            closed_mailbox_with_raised_flag: 'Food & Objects',
            pencil: 'Food & Objects',
            bride_with_veil: 'Smileys & People',
            restroom: 'Symbols',
            cloud: 'Travel & Places',
            japanese_free_of_charge_button: 'Symbols',
            party_popper: 'Food & Objects',
            boy: 'Smileys & People',
            rice_ball: 'Food & Objects',
            glasses: 'Smileys & People',
            tear_off_calendar: 'Food & Objects',
            umbrella_with_rain_drops: 'Travel & Places',
            banana: 'Food & Objects',
            fearful: 'Smileys & People',
            ferris_wheel: 'Travel & Places',
            i_information: 'Symbols',
            person_swimming: 'Smileys & People',
            clipboard: 'Food & Objects',
            anxious_with_sweat: 'Smileys & People',
            bread: 'Food & Objects',
            palm_tree: 'Animals & Nature',
            loudspeaker: 'Food & Objects',
            game_die: 'Food & Objects',
            diamond_suit: 'Food & Objects',
            high_speed_train: 'Travel & Places',
            free_button: 'Symbols',
            videocassette: 'Food & Objects',
            recycling_symbol: 'Symbols',
            link: 'Food & Objects',
            spouting_whale: 'Animals & Nature',
            nut_and_bolt: 'Food & Objects',
            heavy_large_circle: 'Symbols',
            teacup_without_handle: 'Food & Objects',
            green_book: 'Food & Objects',
            cityscape_at_dusk: 'Travel & Places',
            beaming_with_smiling_eyes: 'Smileys & People',
            confounded: 'Smileys & People',
            left_arrow_curving_right: 'Symbols',
            syringe: 'Food & Objects',
            speaker_low_volume: 'Food & Objects',
            pisces: 'Symbols',
            graduation_cap: 'Smileys & People',
            fast_up_button: 'Symbols',
            delivery_truck: 'Travel & Places',
            upwards_button: 'Symbols',
            left_arrow: 'Symbols',
            oncoming_automobile: 'Travel & Places',
            automobile: 'Travel & Places',
            italy: 'Travel & Places',
            floppy_disk: 'Food & Objects',
            down_arrow: 'Symbols',
            roller_coaster: 'Travel & Places',
            raised_hand: 'Smileys & People',
            keycap_zero: 'Symbols',
            bookmark: 'Food & Objects',
            hot_springs: 'Travel & Places',
            first_quarter_moon_face: 'Travel & Places',
            curly_loop: 'Symbols',
            yellow_heart: 'Smileys & People',
            left_luggage: 'Symbols',
            office_building: 'Travel & Places',
            pot_of_food: 'Food & Objects',
            tent: 'Travel & Places',
            tiger_face: 'Animals & Nature',
            bicycle: 'Travel & Places',
            black_nib: 'Food & Objects',
            hospital: 'Travel & Places',
            exclamation_mark: 'Symbols',
            up_left_arrow: 'Symbols',
            twelve_oclock: 'Travel & Places',
            alien: 'Smileys & People',
            baby_angel: 'Smileys & People',
            large_orange_diamond: 'Symbols',
            white_large_square: 'Symbols',
            cat: 'Animals & Nature',
            keycap_four: 'Symbols',
            smiling_with_horns: 'Smileys & People',
            love_letter: 'Smileys & People',
            aries: 'Symbols',
            smiling_with_halo: 'Smileys & People',
            right_arrow_curving_up: 'Symbols',
            right_arrow: 'Symbols',
            expressionless: 'Smileys & People',
            high_voltage: 'Travel & Places',
            ghost: 'Smileys & People',
            man_and_woman_holding_hands: 'Smileys & People',
            reverse_button: 'Symbols',
            eight_pointed_star: 'Symbols',
            paperclip: 'Food & Objects',
            mobile_phone: 'Food & Objects',
            two_oclock: 'Travel & Places',
            sun_with: 'Travel & Places',
            hammer: 'Food & Objects',
            camera: 'Food & Objects',
            heavy_minus_sign: 'Symbols',
            c_copyright: 'Symbols',
            magnifying_glass_tilted_right: 'Food & Objects',
            kissing: 'Smileys & People',
            black_circle: 'Symbols',
            thumbs_up: 'Smileys & People',
            man_with_chinese_cap: 'Smileys & People',
            shower: 'Food & Objects',
            dim_button: 'Symbols',
            straight_ruler: 'Food & Objects',
            first_quarter_moon: 'Travel & Places',
            cocktail_glass: 'Food & Objects',
            with_open_mouth: 'Smileys & People',
            glowing_star: 'Travel & Places',
            running_shoe: 'Smileys & People',
            five_oclock: 'Travel & Places',
            bank: 'Travel & Places',
            police_car_light: 'Travel & Places',
            honeybee: 'Animals & Nature',
            triangular_ruler: 'Food & Objects',
            sun_behind_cloud: 'Travel & Places',
            skis: 'Food & Objects',
            dolphin: 'Animals & Nature',
            blossom: 'Animals & Nature',
            fallen_leaf: 'Animals & Nature',
            person_rowing_boat: 'Smileys & People',
            newspaper: 'Food & Objects',
            customs: 'Symbols',
            currency_exchange: 'Food & Objects',
            trident_emblem: 'Symbols',
            crying: 'Smileys & People',
            shuffle_tracks_button: 'Symbols',
            frog: 'Animals & Nature',
            flexed_biceps: 'Smileys & People',
            fast_forward_button: 'Symbols',
            person_frowning: 'Smileys & People',
            person_gesturing_ok: 'Smileys & People',
            person_bowing: 'Smileys & People',
            alien_monster: 'Smileys & People',
            input_numbers: 'Symbols',
            notebook: 'Food & Objects',
            play_button: 'Symbols',
            heart_with_arrow: 'Smileys & People',
            old_man: 'Smileys & People',
            japanese_service_charge_button: 'Symbols',
            locked_with_pen: 'Food & Objects',
            ok_button: 'Symbols',
            red_heart: 'Smileys & People',
            input_latin_uppercase: 'Symbols',
            sport_utility_vehicle: 'Travel & Places',
            person_taking_bath: 'Smileys & People',
            united_kingdom: 'Travel & Places',
            beating_heart: 'Smileys & People',
            bookmark_tabs: 'Food & Objects',
            sparkling_heart: 'Smileys & People',
            angry: 'Smileys & People',
            up_right_arrow: 'Symbols',
            leaf_fluttering_in_wind: 'Animals & Nature',
            globe_showing_asia_australia: 'Travel & Places',
            chart_increasing_with_yen: 'Food & Objects',
            mens_room: 'Symbols',
            japanese_no_vacancy_button: 'Symbols',
            bar_chart: 'Food & Objects',
            wrapped_gift: 'Food & Objects',
            speaker_medium_volume: 'Food & Objects',
            bikini: 'Smileys & People',
            fuel_pump: 'Travel & Places',
            victory_hand: 'Smileys & People',
            broken_heart: 'Smileys & People',
            womans_sandal: 'Smileys & People',
            kimono: 'Smileys & People',
            grinning_cat: 'Smileys & People',
            postbox: 'Food & Objects',
            ophiuchus: 'Symbols',
            pistol: 'Food & Objects',
            kissing_with_smiling_eyes: 'Smileys & People',
            pear: 'Food & Objects',
            map_of_japan: 'Travel & Places',
            star: 'Travel & Places',
            fishing_pole: 'Food & Objects',
            fish_cake_with_swirl: 'Food & Objects',
            dog_face: 'Animals & Nature',
            with_steam_from_nose: 'Smileys & People',
            nine_oclock: 'Travel & Places',
            elephant: 'Animals & Nature',
            running_shirt: 'Food & Objects',
            downwards_button: 'Symbols',
            watermelon: 'Food & Objects',
            bus: 'Travel & Places',
            smiling_with_sunglasses: 'Smileys & People',
            train: 'Travel & Places',
            japanese_application_button: 'Symbols',
            kitchen_knife: 'Food & Objects',
            speaker_high_volume: 'Food & Objects',
            t_shirt: 'Smileys & People',
            slot_machine: 'Food & Objects',
            japanese_prohibited_button: 'Symbols',
            poultry_leg: 'Food & Objects',
            with_tears_of_joy: 'Smileys & People',
            no_smoking: 'Symbols',
            guard: 'Smileys & People',
            person_raising_hand: 'Smileys & People',
            repeat_button: 'Symbols',
            girl: 'Smileys & People',
            aquarius: 'Symbols',
            bell_with_slash: 'Food & Objects',
            warning: 'Symbols',
            smirking: 'Smileys & People',
            red_triangle_pointed_down: 'Symbols',
            ten_thirty: 'Travel & Places',
            atm_sign: 'Symbols',
            globe_showing_americas: 'Travel & Places',
            yen_banknote: 'Food & Objects',
            snowman_without_snow: 'Travel & Places',
            ten_oclock: 'Travel & Places',
            person_wearing_turban: 'Smileys & People',
            last_quarter_moon: 'Travel & Places',
            tropical_drink: 'Food & Objects',
            locked_with_key: 'Food & Objects',
            winking: 'Smileys & People',
            sagittarius: 'Symbols',
            dizzy: 'Smileys & People',
            persevering: 'Smileys & People',
            children_crossing: 'Symbols',
            grimacing: 'Smileys & People',
            repeat_single_button: 'Symbols',
            counterclockwise_arrows_button: 'Symbols',
            red_triangle_pointed_up: 'Symbols',
            french_fries: 'Food & Objects',
            grinning_with_smiling_eyes: 'Smileys & People',
            articulated_lorry: 'Travel & Places',
            taurus: 'Symbols',
            department_store: 'Travel & Places',
            pager: 'Food & Objects',
            anger_symbol: 'Smileys & People',
            mountain_cableway: 'Travel & Places',
            cinema: 'Symbols',
            red_circle: 'Symbols',
            euro_banknote: 'Food & Objects',
            lipstick: 'Smileys & People',
            inbox_tray: 'Food & Objects',
            o_button_blood_type: 'Symbols',
            green_apple: 'Food & Objects',
            small_orange_diamond: 'Symbols',
            collision: 'Smileys & People',
            envelope_with_arrow: 'Food & Objects',
            wind_chime: 'Food & Objects',
            hourglass_done: 'Travel & Places',
            cool_button: 'Symbols',
            minibus: 'Travel & Places',
            custard: 'Food & Objects',
            open_mailbox_with_raised_flag: 'Food & Objects',
            one_oclock: 'Travel & Places',
            no_pedestrians: 'Symbols',
            thumbs_down: 'Smileys & People',
            saxophone: 'Food & Objects',
            clinking_beer_mugs: 'Food & Objects',
            deciduous_tree: 'Animals & Nature',
            monkey: 'Animals & Nature',
            heart_decoration: 'Smileys & People',
            flag_in_hole: 'Food & Objects',
            volcano: 'Travel & Places',
            green_heart: 'Smileys & People',
            taxi: 'Travel & Places',
            books: 'Food & Objects',
            page_with_curl: 'Food & Objects',
            spaghetti: 'Food & Objects',
            watch: 'Travel & Places',
            question_mark: 'Symbols',
            metro: 'Travel & Places',
            nose: 'Smileys & People',
            double_exclamation_mark: 'Symbols',
            rose: 'Animals & Nature',
            white_question_mark: 'Symbols',
            flower_playing_cards: 'Food & Objects',
            e_mail: 'Food & Objects',
            tennis: 'Food & Objects',
            ship: 'Travel & Places',
            telephone_receiver: 'Food & Objects',
            horse: 'Animals & Nature',
            sunrise: 'Travel & Places',
            germany: 'Travel & Places',
            three_thirty: 'Travel & Places',
            weary_cat: 'Smileys & People',
            leopard: 'Animals & Nature',
            disappointed: 'Smileys & People',
            index_pointing_up: 'Smileys & People',
            input_latin_letters: 'Symbols',
            tram: 'Travel & Places',
            keycap_eight: 'Symbols',
            cooking: 'Food & Objects',
            aerial_tramway: 'Travel & Places',
            japanese_open_for_business_button: 'Symbols',
            mouse: 'Animals & Nature',
            person_mountain_biking: 'Smileys & People',
            cat_face: 'Animals & Nature',
            speak_no_evil_monkey: 'Smileys & People',
            microphone: 'Food & Objects',
            tomato: 'Food & Objects',
            person_running: 'Smileys & People',
            flushed: 'Smileys & People',
            with_tongue: 'Smileys & People',
            camel: 'Animals & Nature',
            rocket: 'Travel & Places',
            up_button: 'Symbols',
            red_apple: 'Food & Objects',
            eleven_thirty: 'Travel & Places',
            video_camera: 'Food & Objects',
            japanese_dolls: 'Food & Objects',
            eight_spoked_asterisk: 'Symbols',
            dragon: 'Animals & Nature',
            wedding: 'Travel & Places',
            oncoming_fist: 'Smileys & People',
            candy: 'Food & Objects',
            with_medical_mask: 'Smileys & People',
            fast_down_button: 'Symbols',
            shooting_star: 'Travel & Places',
            fork_and_knife: 'Food & Objects',
            door: 'Food & Objects',
            bug: 'Animals & Nature',
            a_button_blood_type: 'Symbols',
            black_medium_small_square: 'Symbols',
            sailboat: 'Travel & Places',
            joker: 'Food & Objects',
            shaved_ice: 'Food & Objects',
            two_women_holding_hands: 'Smileys & People',
            person_biking: 'Smileys & People',
            womans_clothes: 'Smileys & People',
            chicken: 'Animals & Nature',
            m_circled_m: 'Symbols',
            cooked_rice: 'Food & Objects',
            seedling: 'Animals & Nature',
            soft_ice_cream: 'Food & Objects',
            keycap_nine: 'Symbols',
            japanese_here_button: 'Symbols',
            weary: 'Smileys & People',
            pile_of_poo: 'Smileys & People',
            black_large_square: 'Symbols',
            satellite_antenna: 'Food & Objects',
            winking_with_tongue: 'Smileys & People',
            footprints: 'Smileys & People',
            cancer: 'Symbols',
            four_thirty: 'Travel & Places',
            waning_crescent_moon: 'Travel & Places',
            koala: 'Animals & Nature',
            japan: 'Travel & Places',
            smiling_cat_with_heart_eyes: 'Smileys & People',
            keycap_one: 'Symbols',
            revolving_hearts: 'Smileys & People',
            fire: 'Travel & Places',
            tangerine: 'Food & Objects',
            up_arrow: 'Symbols',
            open_book: 'Food & Objects',
            spain: 'Travel & Places',
            house_with_garden: 'Travel & Places',
            blue_circle: 'Symbols',
            cross_mark: 'Symbols',
            mouse_face: 'Animals & Nature',
            magnifying_glass_tilted_left: 'Food & Objects',
            telephone: 'Food & Objects',
            ram: 'Animals & Nature',
            sunset: 'Travel & Places',
            page_facing_up: 'Food & Objects',
            bust_in_silhouette: 'Smileys & People',
            downcast_with_sweat: 'Smileys & People',
            chocolate_bar: 'Food & Objects',
            six_thirty: 'Travel & Places',
            money_bag: 'Food & Objects',
            roasted_sweet_potato: 'Food & Objects',
            neutral: 'Smileys & People',
            astonished: 'Smileys & People',
            ticket: 'Food & Objects',
            sunflower: 'Animals & Nature',
            zzz: 'Smileys & People',
            panda: 'Animals & Nature',
            mouth: 'Smileys & People',
            heavy_division_sign: 'Symbols',
            hushed: 'Smileys & People',
            passport_control: 'Symbols',
            two_thirty: 'Travel & Places',
            nail_polish: 'Smileys & People',
            carp_streamer: 'Food & Objects',
            dog: 'Animals & Nature',
            steaming_bowl: 'Food & Objects',
            full_moon_face: 'Travel & Places',
            hatching_chick: 'Animals & Nature',
            snowflake: 'Travel & Places',
            vibration_mode: 'Symbols',
            paw_prints: 'Animals & Nature',
            heart_suit: 'Food & Objects',
            kissing_cat: 'Smileys & People',
            oncoming_taxi: 'Travel & Places',
            battery: 'Food & Objects',
            envelope: 'Food & Objects',
            gemini: 'Symbols',
            whale: 'Animals & Nature',
            dizzy_face: 'Smileys & People',
            front_facing_baby_chick: 'Animals & Nature',
            pensive: 'Smileys & People',
            no_bicycles: 'Symbols',
            bridge_at_night: 'Travel & Places',
            anguished: 'Smileys & People',
            necktie: 'Smileys & People',
            memo: 'Food & Objects',
            balloon: 'Food & Objects',
            input_symbols: 'Symbols',
            school: 'Travel & Places',
            china: 'Travel & Places',
            telescope: 'Food & Objects',
            wheelchair_symbol: 'Symbols',
            japanese_not_free_of_charge_button: 'Symbols',
            last_quarter_moon_face: 'Travel & Places',
            france: 'Travel & Places',
            japanese_post_office: 'Travel & Places',
            keycap_two: 'Symbols',
            radio: 'Food & Objects',
            kiss: 'Smileys & People',
            baby_chick: 'Animals & Nature',
            part_alternation_mark: 'Symbols',
            factory: 'Travel & Places',
            leo: 'Symbols',
            virgo: 'Symbols',
            church: 'Travel & Places',
            dragon_face: 'Animals & Nature',
            tropical_fish: 'Animals & Nature',
            closed_book: 'Food & Objects',
            small_blue_diamond: 'Symbols',
            japanese_discount_button: 'Symbols',
            japanese_acceptable_button: 'Symbols',
            princess: 'Smileys & People',
            white_small_square: 'Symbols',
            white_medium_small_square: 'Symbols',
            smiling_with_heart_eyes: 'Smileys & People',
            suspension_railway: 'Travel & Places',
            crescent_moon: 'Travel & Places',
            sparkles: 'Food & Objects',
            fax_machine: 'Food & Objects',
            high_heeled_shoe: 'Smileys & People',
            south_korea: 'Travel & Places',
            mountain_railway: 'Travel & Places',
            mushroom: 'Food & Objects',
            monorail: 'Travel & Places',
            person_gesturing_no: 'Smileys & People',
            pine_decoration: 'Food & Objects',
            grinning: 'Smileys & People',
            right_arrow_curving_left: 'Symbols',
            p_button: 'Symbols',
            seven_thirty: 'Travel & Places',
            dashing_away: 'Smileys & People',
            grinning_squinting: 'Smileys & People',
            eggplant: 'Food & Objects',
            crown: 'Smileys & People',
            three_oclock: 'Travel & Places',
            grinning_with_big_eyes: 'Smileys & People',
            unlocked: 'Food & Objects',
            horse_racing: 'Smileys & People',
            money_with_wings: 'Food & Objects',
            japanese_vacancy_button: 'Symbols',
            baby_bottle: 'Food & Objects',
            no_mobile_phones: 'Symbols',
            top_arrow: 'Symbols',
            turtle: 'Animals & Nature',
            carousel_horse: 'Travel & Places',
            musical_note: 'Food & Objects',
            old_woman: 'Smileys & People',
            chestnut: 'Food & Objects',
            two_men_holding_hands: 'Smileys & People',
            white_heavy_check_mark: 'Symbols',
            dvd: 'Food & Objects',
            non_potable_water: 'Symbols',
            down_left_arrow: 'Symbols',
            airplane: 'Travel & Places',
            tulip: 'Animals & Nature',
            headphone: 'Food & Objects',
            sleepy: 'Smileys & People',
            double_curly_loop: 'Symbols',
            oden: 'Food & Objects',
            blue_heart: 'Smileys & People',
            up_down_arrow: 'Symbols',
            man: 'Smileys & People',
            see_no_evil_monkey: 'Smileys & People',
            dango: 'Food & Objects',
            open_mailbox_with_lowered_flag: 'Food & Objects',
            flashlight: 'Food & Objects',
            castle: 'Travel & Places',
            white_circle: 'Symbols',
            r_registered: 'Symbols',
            frowning_with_open_mouth: 'Smileys & People',
            microscope: 'Food & Objects',
            oncoming_police_car: 'Travel & Places',
            people_with_bunny_ears: 'Smileys & People',
            television: 'Food & Objects',
            baggage_claim: 'Symbols',
            blowfish: 'Animals & Nature',
            backhand_index_pointing_down: 'Smileys & People',
            dotted_six_pointed_star: 'Symbols',
            megaphone: 'Food & Objects',
            cross_mark_button: 'Symbols',
            new_moon: 'Travel & Places',
            convenience_store: 'Travel & Places',
            sparkler: 'Food & Objects',
            relieved: 'Smileys & People',
            clapper_board: 'Food & Objects',
            eight_oclock: 'Travel & Places',
            hamburger: 'Food & Objects',
            scorpio: 'Symbols',
            fast_reverse_button: 'Symbols',
            doughnut: 'Food & Objects',
            backhand_index_pointing_left: 'Smileys & People',
            optical_disk: 'Food & Objects',
            jeans: 'Smileys & People',
            japanese_passing_grade_button: 'Symbols',
            crossed_flags: 'Travel & Places',
            zhu_japanese_congratulations_button: 'Symbols',
            artist_palette: 'Food & Objects',
            performing_arts: 'Food & Objects',
            chequered_flag: 'Travel & Places',
            ab_button_blood_type: 'Symbols',
            tanabata_tree: 'Food & Objects',
            locked: 'Food & Objects',
            growing_heart: 'Smileys & People',
            video_game: 'Food & Objects',
            rooster: 'Animals & Nature',
            musical_notes: 'Food & Objects',
            snowboarder: 'Smileys & People',
            hamster: 'Animals & Nature',
            maple_leaf: 'Animals & Nature',
            purse: 'Smileys & People',
            snail: 'Animals & Nature',
            couple_with_heart: 'Smileys & People',
            blue_book: 'Food & Objects',
            large_blue_diamond: 'Symbols',
            pound_banknote: 'Food & Objects',
            handbag: 'Smileys & People',
            antenna_bars: 'Symbols',
            bullet_train: 'Travel & Places',
            fried_shrimp: 'Food & Objects',
            back_arrow: 'Symbols',
            left_right_arrow: 'Symbols',
            laptop_computer: 'Food & Objects',
            sos_button: 'Symbols',
            black_small_square: 'Symbols',
            statue_of_liberty: 'Travel & Places',
            horse_face: 'Animals & Nature',
            cyclone: 'Travel & Places',
            eleven_oclock: 'Travel & Places',
            grapes: 'Food & Objects',
            one_thirty: 'Travel & Places',
            horizontal_traffic_light: 'Travel & Places',
            keycap_five: 'Symbols',
            construction_worker: 'Smileys & People',
            trophy: 'Food & Objects',
            guitar: 'Food & Objects',
            honey_pot: 'Food & Objects',
            gem_stone: 'Smileys & People',
            down_right_arrow: 'Symbols',
            lady_beetle: 'Animals & Nature',
            incoming_envelope: 'Food & Objects',
            skull: 'Smileys & People',
            evergreen_tree: 'Animals & Nature',
            baby_symbol: 'Symbols',
            radio_button: 'Symbols',
            school_backpack: 'Smileys & People',
            family: 'Smileys & People',
            no_one_under_eighteen: 'Symbols',
            prohibited: 'Symbols',
            water_buffalo: 'Animals & Nature',
            boar: 'Animals & Nature',
            cactus: 'Animals & Nature',
            rabbit: 'Animals & Nature',
            input_latin_lowercase: 'Symbols',
            scissors: 'Food & Objects',
            screaming_in_fear: 'Smileys & People',
            sun: 'Travel & Places',
            package: 'Food & Objects',
            locomotive: 'Travel & Places',
            person_surfing: 'Smileys & People',
            cow_face: 'Animals & Nature',
            sake: 'Food & Objects',
            love_hotel: 'Travel & Places',
            bell: 'Food & Objects',
            cookie: 'Food & Objects',
            closed_umbrella: 'Travel & Places',
            japanese_castle: 'Travel & Places',
            open_hands: 'Smileys & People',
            raised_fist: 'Smileys & People',
            clapping_hands: 'Smileys & People',
            tongue: 'Smileys & People',
            unamused: 'Smileys & People',
            lemon: 'Food & Objects',
            crying_cat: 'Smileys & People',
            keycap_ten: 'Symbols',
            electric_plug: 'Food & Objects',
            crystal_ball: 'Food & Objects',
            direct_hit: 'Food & Objects',
            movie_camera: 'Food & Objects',
            bowling: 'Food & Objects',
            toilet: 'Food & Objects',
            baseball: 'Food & Objects',
            postal_horn: 'Food & Objects',
            womans_hat: 'Smileys & People',
            moon_viewing_ceremony: 'Food & Objects',
            sheaf_of_rice: 'Animals & Nature',
            anchor: 'Travel & Places',
            foggy: 'Travel & Places',
            white_exclamation_mark: 'Symbols',
            jack_o_lantern: 'Food & Objects',
            key: 'Food & Objects',
            pool_: 'Food & Objects',
            pouting: 'Smileys & People',
            ballot_box_with_check: 'Symbols',
            mobile_phone_with_arrow: 'Food & Objects',
            santa_claus: 'Smileys & People',
            waxing_gibbous_moon: 'Travel & Places',
            folded_hands: 'Smileys & People',
            bouquet: 'Animals & Nature',
            diamond_with_a_dot: 'Symbols',
            pig_nose: 'Animals & Nature',
            rainbow: 'Travel & Places',
            ambulance: 'Travel & Places',
            vs_button: 'Symbols',
            hourglass_not_done: 'Travel & Places',
            clockwise_vertical_arrows: 'Symbols',
            kiss_mark: 'Smileys & People',
            oncoming_bus: 'Travel & Places',
            fish: 'Animals & Nature',
            dress: 'Smileys & People',
            hundred_points: 'Symbols',
            goat: 'Animals & Nature',
            light_rail: 'Travel & Places',
            person_getting_haircut: 'Smileys & People',
            night_with_stars: 'Travel & Places',
            octopus: 'Animals & Nature',
            woman_dancing: 'Smileys & People',
            bright_button: 'Symbols',
            tram_car: 'Travel & Places',
            ear_of_corn: 'Food & Objects',
            busts_in_silhouette: 'Smileys & People',
            sleeping: 'Smileys & People',
            united_states: 'Travel & Places',
            purple_heart: 'Smileys & People',
            ogre: 'Smileys & People',
            ledger: 'Food & Objects',
            squinting_with_tongue: 'Smileys & People',
            mount_fuji: 'Travel & Places',
            hibiscus: 'Animals & Nature',
            backhand_index_pointing_right: 'Smileys & People',
            keycap_three: 'Symbols',
            heavy_dollar_sign: 'Food & Objects',
            clutch_bag: 'Smileys & People',
            potable_water: 'Symbols',
            briefcase: 'Food & Objects',
            shortcake: 'Food & Objects',
            person_getting_massage: 'Smileys & People',
            fountain: 'Travel & Places',
            fire_engine: 'Travel & Places',
            file_folder: 'Food & Objects',
            white_medium_square: 'Symbols',
            cow: 'Animals & Nature',
            cat_with_tears_of_joy: 'Smileys & People',
            four_oclock: 'Travel & Places',
            grinning_with_sweat: 'Smileys & People',
            curry_rice: 'Food & Objects',
            monkey_face: 'Animals & Nature',
            cherry_blossom: 'Animals & Nature',
            two_hump_camel: 'Animals & Nature',
            worried: 'Smileys & People',
            top_hat: 'Smileys & People',
            sunrise_over_mountains: 'Travel & Places',
            ring: 'Smileys & People',
            soon_arrow: 'Symbols',
            pouting_cat: 'Smileys & People',
            pizza: 'Food & Objects',
            hotel: 'Travel & Places',
            sushi: 'Food & Objects',
            four_leaf_clover: 'Animals & Nature',
            peach: 'Food & Objects',
            notebook_with_decorative_cover: 'Food & Objects',
            meat_on_bone: 'Food & Objects',
            violin: 'Food & Objects',
            spade_suit: 'Food & Objects',
            wine_glass: 'Food & Objects',
            pineapple: 'Food & Objects',
            round_pushpin: 'Food & Objects',
            water_wave: 'Travel & Places',
            computer_disk: 'Food & Objects',
            seven_oclock: 'Travel & Places',
            scroll: 'Food & Objects',
            tractor: 'Travel & Places',
            on_arrow: 'Symbols',
            ng_button: 'Symbols',
            grinning_cat_with_smiling_eyes: 'Smileys & People',
            helicopter: 'Travel & Places',
            confused: 'Smileys & People',
            libra: 'Symbols',
            white_flower: 'Animals & Nature',
            b_button_blood_type: 'Symbols',
            trolleybus: 'Travel & Places',
            sparkle: 'Symbols',
            ok_hand: 'Smileys & People',
            basketball: 'Food & Objects',
            vertical_traffic_light: 'Travel & Places',
            tired: 'Smileys & People',
            pushpin: 'Food & Objects',
            eyes: 'Smileys & People',
            sad_but_relieved: 'Smileys & People',
            smiling_with_smiling_eyes: 'Smileys & People',
            new_moon_face: 'Travel & Places',
            person_tipping_hand: 'Smileys & People',
            bento_box: 'Food & Objects',
            no_entry: 'Symbols',
            bus_stop: 'Travel & Places',
            six_oclock: 'Travel & Places',
            police_car: 'Travel & Places',
            smiling: 'Smileys & People',
            hear_no_evil_monkey: 'Smileys & People',
            milky_way: 'Travel & Places',
            outbox_tray: 'Food & Objects',
            droplet: 'Travel & Places',
            police_officer: 'Smileys & People',
            wolf: 'Animals & Nature',
            japanese_reserved_button: 'Symbols',
            cigarette: 'Food & Objects',
            moai: 'Food & Objects',
            post_office: 'Travel & Places',
            circus_tent: 'Travel & Places',
            club_suit: 'Food & Objects',
            mahjong_red_dragon: 'Food & Objects',
            keycap_six: 'Symbols',
            bomb: 'Smileys & People',
            heavy_multiplication_x: 'Symbols',
            christmas_tree: 'Food & Objects',
            muted_speaker: 'Food & Objects',
            without_mouth: 'Smileys & People',
            trumpet: 'Food & Objects',
            pig: 'Animals & Nature',
            sweat_droplets: 'Smileys & People',
            open_file_folder: 'Food & Objects',
            ewe: 'Animals & Nature',
            lollipop: 'Food & Objects',
            woman: 'Smileys & People',
            exclamation_question_mark: 'Symbols',
            black_medium_square: 'Symbols',
            full_moon: 'Travel & Places',
            name_badge: 'Symbols',
            angry_with_horns: 'Smileys & People',
            heavy_check_mark: 'Symbols',
            bathtub: 'Food & Objects',
            dollar_banknote: 'Food & Objects',
            water_closet: 'Symbols',
            musical_score: 'Food & Objects',
            bird: 'Animals & Nature',
            litter_in_bin_sign: 'Symbols',
            womans_boot: 'Smileys & People',
            penguin: 'Animals & Nature',
            closed_mailbox_with_lowered_flag: 'Food & Objects',
            triangular_flag: 'Travel & Places',
            rat: 'Animals & Nature',
            calendar: 'Food & Objects',
            hot_beverage: 'Food & Objects',
            twelve_thirty: 'Travel & Places',
            bear: 'Animals & Nature',
            globe_with_meridians: 'Travel & Places',
            tm_trade_mark: 'Symbols',
            construction: 'Travel & Places',
            american_football: 'Food & Objects',
            rabbit_face: 'Animals & Nature',
            strawberry: 'Food & Objects',
            orange_book: 'Food & Objects',
            womens_room: 'Symbols',
            five_thirty: 'Travel & Places',
            heart_with_ribbon: 'Smileys & People',
            crocodile: 'Animals & Nature',
            herb: 'Animals & Nature',
            railway_car: 'Travel & Places',
            confetti_ball: 'Food & Objects',
            wavy_dash: 'Symbols',
            eight_thirty: 'Travel & Places',
            mobile_phone_off: 'Symbols',
            station: 'Travel & Places',
            melon: 'Food & Objects',
            japanese_symbol_for_beginner: 'Symbols',
            ribbon: 'Food & Objects',
            card_index: 'Food & Objects',
            seat: 'Travel & Places',
            nine_thirty: 'Travel & Places',
            kissing_with_closed_eyes: 'Smileys & People',
            alarm_clock: 'Travel & Places',
            thought_balloon: 'Smileys & People',
            id_button: 'Symbols',
            tokyo_tower: 'Travel & Places',
            loudly_crying: 'Smileys & People',
            globe_showing_europe_africa: 'Travel & Places',
            beer_mug: 'Food & Objects',
            russia: 'Travel & Places',
            raising_hands: 'Smileys & People',
            soccer_ball: 'Food & Objects',
            ant: 'Animals & Nature',
            barber_pole: 'Travel & Places',
            goblin: 'Smileys & People',
            poodle: 'Animals & Nature',
            cat_with_wry_smile: 'Smileys & People',
            tiger: 'Animals & Nature',
            baby: 'Smileys & People',
            japanese_bargain_button: 'Symbols',
            capricorn: 'Symbols',
            savoring_food: 'Smileys & People',
            waning_gibbous_moon: 'Travel & Places',
            right_arrow_curving_down: 'Symbols',
            end_arrow: 'Symbols',
            pig_face: 'Animals & Nature',
            blond_haired_person: 'Smileys & People',
            blowing_a_kiss: 'Smileys & People',
            black_square_button: 'Symbols',
            pill: 'Food & Objects',
            light_bulb: 'Food & Objects',
            chart_decreasing: 'Food & Objects',
            waving_hand: 'Smileys & People',
            keycap_hash: 'Symbols',
            mans_shoe: 'Smileys & People',
            person_pouting: 'Smileys & People',
            wrench: 'Food & Objects',
            speech_balloon: 'Smileys & People',
            rugby_football: 'Food & Objects',
            heavy_plus_sign: 'Symbols',
            ear: 'Smileys & People',
            person_walking: 'Smileys & People',
            backhand_index_pointing_up: 'Smileys & People',
            birthday_cake: 'Food & Objects',
            no_littering: 'Symbols',
            white_square_button: 'Symbols',
            snake: 'Animals & Nature',
            fireworks: 'Food & Objects',
            musical_keyboard: 'Food & Objects',
            new_button: 'Symbols',
            ice_cream: 'Food & Objects',
            red_paper_lantern: 'Food & Objects',
            waxing_crescent_moon: 'Travel & Places',
            keycap_seven: 'Symbols',
            cherries: 'Food & Objects',
            credit_card: 'Food & Objects',
            spiral_shell: 'Animals & Nature',
            house: 'Travel & Places',
            mi_japanese_secret_button: 'Symbols',
            ox: 'Animals & Nature',
            speedboat: 'Travel & Places',
            japanese_monthly_amount_button: 'Symbols',
            two_hearts: 'Smileys & People',
            chart_increasing: 'Food & Objects',
            rice_cracker: 'Food & Objects',
            cl_button: 'Symbols'
        };
    }
})();
